# Site Settings
baseurl: ""

# Features Setting
# Turn subpages on or off
publications: True
presentations: False
blog: False

# Language of the website
lang: en

social:
  name: Florian Feiler
  links:
    - https://twitter.com/fffeiler
    - https://github.com/ffeiler
locale: en_GB

# Page Settings
theme_settings:
  title: Grape Academic Theme
  experience_title: EXPERIENCE
  interests_title: RESEARCH INTERESTS
  skills_title: SKILLS
  awards_title: AWARDS
  projects_title: # TODO projects
  recentpubs_title: RECENT PUBLICATIONS

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Settings
sass:
  sass_dir: _sass
  style: :compressed
plugins: ['jekyll-paginate', 'jekyll/scholar', 'jekyll-seo-tag']
bootstrap:
  assets: true

# Bibliography settings
scholar:
  bibliography: publications.bib
  bibliography_template: pubstemplate
  style: apa
  locale: en
  last_name: Feiler
  first_name: [Florian, F.]
  sort_by: year,month
  order: descending,ascending

filtered_bibtex_keywords: [abbr, abstract, arxiv, bibtex_show, html, pdf, selected, supp, blog, code, poster, slides, website] # Filter out certain bibtex entry keywords used internally from the bib output

academicons:
  version: "1.9.1"
  integrity: "sha256-i1+4qU2G2860dGGIOJscdC30s9beBXjFfzjWLjBRsBg="
fontawesome:
  version: "6.4.0"
  integrity: "ssha256-HtsXJanqjKTc8vVQjO4YMhiqFoXkfBsjBWcX91T1jr8="
jquery:
  version: "3.6.0"
  integrity: "sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
